backend:
  name: git-gateway
  branch: main

media_folder: "assets/produits"
public_folder: "/assets/produits"

locale: "fr"

collections:
  - name: "creations"
    label: "Mes créations"
    files:
      - file: "data/products.json"
        label: "Galerie de créations"
        name: "galerie"
        fields:
          - label: "Créations"
            name: "produits"
            widget: "list"
            label_singular: "Création"
            summary: "{{fields.nom}}"
            fields:
              - {label: "Nom de la création", name: "nom", widget: "string"}
              - label: "Ingrédients"
                name: "ingredients"
                widget: "list"
                field: {label: "Ingrédient", name: "ingredient", widget: "string"}
              - {label: "Photo", name: "image", widget: "image", required: false, choose_url: false}
